# Generated by Django 5.2.11 on 2026-02-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelstation",
            name="opis_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fuelstation",
            name="rack_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="fuelstation",
            name="state",
            field=models.CharField(max_length=100),
        ),
    ]
